### ISSUE TITLE
Does not work with Ansible 2.10+

### ISSUE THREAD

**Issue by Chilinot** [diodonfrost/ansible-role-amazon-ssm#3]
##### SUMMARY
Ansible 2.10 changed the namespaces of builtin modules.

##### STEPS TO REPRODUCE
Run a basic playbook calling this role using Ansible 2.10+.

##### EXPECTED RESULTS
Not error out.

##### ACTUAL RESULTS
```
ERROR! couldn't resolve module/action 'win_service'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/xxx/ansible/playbooks/roles.galaxy/diodonfrost.amazon_ssm/handlers/main.yml': line 18, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Windows | Restart amazon ssm agent
  ^ here
```

##### ENVIRONMENT
* MacOS Big Sur
* Ansible version 2.10.0
* Python version 3.8.7

**Comment by Chilinot** [comment]
The solution is to call modules with the new namespaced names. Fixing this changes the module call to `ansible.windows.win_service`. However, its possible it would break support for Ansible <= 2.9

**Comment by diodonfrost** [comment]
@Chilinot yes, indeed.
There are several solutions. I'm going to look into this.

**Comment by diodonfrost** [comment]
@Chilinot I am unable to repoduce this error.
I apply this role on an ubuntu 20.04 with ansible 2.10.0 and it works well
ENV:
- Python 3.8.5
- Ansible 2.10.0
- Ansible-base 2.10.0
- Ubuntu 20.04

Molecule testing uses the latest version of Ansible and it works well too.
I also tested this role on Windows with the latest version of Ansible(2.10.6) and I didn't have any problems.

Any idea why does it work ?

**Comment by Chilinot** [comment]
Alright, I have had similar issues before after updating to 2.10.0 which seems to only happen on macos. Perhaps there is a difference in ansible between Linux and macos that causes these issues.

**Comment by Chilinot** [comment]
I tried updating my ansible now, and am now on 2.10.5. It seems my issues are resolved. So i will close this ticket.
